### ISSUE TITLE
Zephyr Hello World C Project (microkernel) not available as a C project template

### ISSUE THREAD

**Issue by belenbarrospena** [todorez/crops#12]
I followed the instructions in 
https://github.com/todorez/crops/wiki

And proceeded to install Eclipse as explained here
https://github.com/todorez/crops/wiki/how-to-use-plugin-on-mac

I completed step 2 "Install the eclipse-crops plugin" without being connected to the Intel network. The note at the end of that section suggests that you need to be connected to the Intel network to be able to install the plugin, but the installation seemed to complete successfully without being connected. The plugin is listed in the Installed Software information:

![installed-software](https://cloud.githubusercontent.com/assets/684113/13526994/bc08e7c2-e203-11e5-8a0e-1aa211d8420e.png)

However, when I went into step 3 and tried to create a new C project, I couldn't see the Zephyr Hello World C Project (microkernel)  option listed in either the 'Project type' or 'Toolchains' lists. 

![c-project-dialog](https://cloud.githubusercontent.com/assets/684113/13526779/4e3b59a6-e202-11e5-9b04-be1ef6a7511d.png)

Thinking that maybe something went wrong during the plugin installation, I connected to the Intel network, went to Help > Install new software and tried to repeat the eclipse-crops plugin installation steps while connected to the Intel network. Unfortunately, Eclipse seems to time out when trying to connect to http://crops.minchev.co.uk/eclipse-plugin/0.1.65.201602141611-mac/

![timingout](https://cloud.githubusercontent.com/assets/684113/13526929/42554696-e203-11e5-9e88-2075f66b54c0.png)

This was the full error log:

eclipse.buildId=4.5.2.M20160212-1500
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.cpp.product -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.cpp.product -data file:/Users/bbarrosp/eclipse/cpp-mars/Eclipse.app/Contents/Eclipse/~/crops-workspace/ -product org.eclipse.epp.package.cpp.product

org.eclipse.equinox.p2.transport.ecf
Error
Fri Mar 04 12:03:14 GMT 2016
Unable to read repository at http://crops.minchev.co.uk/eclipse-plugin/0.1.65.201602141611-mac/content.xml.

java.net.SocketException: Socket closed
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:343)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

So, do I need to be connected to the Intel network to install the Crops plugin? How to I troubleshoot the existing plugin installation? Should I just uninstall the plugin and reinstall it? Thanks!

**Comment by todorez** [comment]
@bavery22 @moto-timo will probably know why this menu is missing

**Comment by bavery22Intel** [comment]
a couple of things:
1) the intel network thing is historical. the co.uk address is outside, so it's not the problem.
2) in the C Project Location, your location is wrong. It should be /Users/bbarosp/crops-workspace.  Right now it's pointing deep into the actual Eclipse Application's folders...  This is derived from the workspace. you can goto File->Switch Workspace to change it.
3) that being said: if I repeat your steps I *still* see the nano/micro zephyr options.  
<img width="1005" alt="screen shot 2016-03-04 at 11 00 51 am" src="https://cloud.githubusercontent.com/assets/17650707/13537218/aa957844-e1f8-11e5-8df7-f9e71f75470e.png">
Here's the Eclipse version I have:
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
Here's the mac version:
10.10.5
Unable to replicate :(

**Comment by bavery22** [comment]
I tried this on a clean mac that had no previous Eclipse installation and couldn't replicate the error. 
Here's a synopsis of what I did. Make sure:
1) You have installed a current Java from Oracle:
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
I used jdk-8u74-macosx-x64.dmg  From a terminal window you should be able to do :
~ bavery$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

2) You use the OOMph Eclipse installer from https://eclipse.org/downloads/ and not the Eclipse Package Downloads. The installer comes from this button:
![screenshot 2016-03-04 16 56 49](https://cloud.githubusercontent.com/assets/2699661/13544380/324eaf72-e22a-11e5-9d1d-3c3251e2ab2e.png)
3) Set your workspace to /users/<username>/crops-workspace
4) Choose File->New C Project and the Zephyr options should appear under the Executables selection.

**Comment by belenbarrospena** [comment]
Updating Java seemed to do the trick. I had java version "1.7.0_79". Installed jdk-8u74-macosx-x64.dmg and now I can see the the Zephyr options in the New C Project dialog. 

Should we add the Java step to the instructions?

**Comment by todorez** [comment]
@belenbarrospena Thanks, I will update the instructions. Installing the JRE should do it.
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by bavery22** [comment]
Nope, needs the jdk. At least it did for my home Mac test.
B

**Comment by todorez** [comment]
The wiki was updated. Closing.
https://github.com/todorez/crops/wiki/how-to-use-plugin-on-mac

**Comment by bavery22** [comment]
ty :)
-b
